### ISSUE TITLE
Symbol Table

### ISSUE THREAD

**Issue by scottcalebc** [scottcalebc/PickleBOL#3]
All functionality for the Symbol table

SymbolTable methods:
 - getSymbol
 - putSymbol
 - initGlobal

SymbolTable entry classes:
 - STEntry
 - STIdentifier
 - STFunction
 - STControl

**Comment by LukeCD12** [comment]
- Added STEntry and its subclasses
- implemented getSymbol, putSymbol, intiGlobal for global symbol table

Note: Small-ish changes may have to be made depending on how Clark wants implementation of user defined functions and their respective symbol tables
